### ISSUE TITLE
Validation of lists

### ISSUE THREAD

**Issue by botzill** [nicolaiarocci/cerberus#220] opened 2016-03-30 09:10 UTC
Hi.

I want to ask if currently cerberus allow us to validate lists? I may have a simple input doc in the list form:

`[{"id": 1}, {"id": 2}]`

Is it possible to validate it? 

I know that I may wrap this in a dict and use the standard validation, but I was wandering if it's possible without dict.

Thx.

**Comment by funkyfuture** [comment] 2016-04-01 11:26
have you (considered to) read the documentation?

**Comment by botzill** [comment] 2016-04-01 11:31
Yes I read the docs and I could not find anything about it. I also did tests and it says:

`cerberus.cerberus.ValidationError: '['1', '2']' is not a document, must be a dict`

That's why I' asking about it. 

Maybe I'm wrong, can you point me into the right  direction?

Thx.

**Comment by funkyfuture** [comment] 2016-04-01 17:06
sorry, i should have read your initial post more carefully. so, no it's not possible and i don't think a method that wraps data and rules into a document is really necessary.

**Comment by jdotjdot** [comment] 2016-04-03 20:19
We ran into this issue as well&mdash;and @funkyfuture I'd respectfully disagree that it's not necessary.  For our use case, we needed exclusively to validate JSON documents that were all top-level arrays.

To fix this, I wrote a `Validator` subclass that takes care of this for you if you initialize it with `is_array=True` by temporarily wrapping your array in a JSON object with the key `rows`, and then unwrapping it when done validating.

Since this was using Cerberus 0.9.2 which didn't yet offer normalization options, I wrote my own normalization method as well.

```python
import copy
from cerberus import Validator
# using Cerberus 0.9.2
import six

class UpgradedValidator(Validator):
    """
    Subclass of Cerberus's Validator that adds some custom types and allows for the document to be a top-level array
        by setting is_array=True
    """

    def __init__(self, *args, **kwargs):
        self.is_array = kwargs.get('is_array', False)
        super(UpgradedValidator, self).__init__(*args, **kwargs)

    def validate(self, document, schema=None, update=False, context=None):

        # This gets confusing because this method seems to be called internally for validation as well
        # and we don't want to add "rows" to sub-schemas as well, only the
        # top-level.

        if self.is_array and not context:  # checking for "context" seems to help with not adding 'rows' to every dict
            schema = schema or self.schema

            if 'rows' not in schema:
                if 'type' in schema:  # is a list
                    schema = {'rows': {'type': 'list',
                                       'required': True, 'schema': schema}}
                else:  # is a dict
                    schema = {'rows': {'type': 'list', 'required': True,
                                       'schema': {'type': 'dict', 'schema': schema}}}

            if 'rows' not in document:
                document = {'rows': document}
        return super(UpgradedValidator, self).validate(document, schema, update, context)

    @property
    def errors(self):
        errors = super(UpgradedValidator, self).errors
        if self.is_array and 'rows' in errors:
            return errors['rows']
        else:
            return errors

    _type_defaults = {
        'integer': 0,
        'list': [],
        'dict': {},
        'string': '',
    }

    def get_type_default(self, type_):
        return self._type_defaults.get(type_)

    def get_default(self, field_schema):
        if 'default' in field_schema:
            return field_schema.get('default')

        if field_schema.get('nullable', False):
            return None

        return self.get_type_default(field_schema['type'])

    def add_defaults_to_doc(self, document, doc_schema):
        new_doc = copy.deepcopy(document)
        for field, field_schema in doc_schema.items():
            if field not in document:
                new_doc[six.u(field)] = self.get_default(field_schema)

        return new_doc

    def normalize_list(self, document, schema=None):
        # Needed to write this because the .normalized() method doesn't come out until Cerberus 0.10
        #  which has not yet been released

        # This is a bit lazy and assumes a list of dicts, since that's what
        # this whole subclass was written for

        schema = schema or self.schema
        schema = schema['rows']['schema'] if 'rows' in schema else schema
        if isinstance(document, (list, tuple, set)):
            return [self.add_defaults_to_doc(doc, schema) for doc in document]
```

**Comment by nicolaiarocci** [comment] 2016-04-04 05:56
I tend to agree with @funkyfuture. While it would be undoubtedly nice to provide list validation out of the box, it is not hard to do so with a custom validator, like @jdotjdot did. In fact custom validators and, in general, the various extension methods offered by the library are there to allow for the catering of scenarios like this one. 

We don't want to end up having to chase and implement core support for all kind of corner/special cases. I am closing this ticker for the time being. We might re-evaluate it in the future when/if 1.0 is out and stable.

**Closed by nicolaiarocci** 2016-04-04 05:56 UTC

**Comment by jdotjdot** [comment] 2016-04-04 06:05
@nicolaiarocci fair enough.  My only disagreements here would be:

1. This particular case wasn't _that_ easy to implement.  It took quite a bit of digging around the Cerberus internals to get right, in particular around the `validate()` method and figuring out to check for `context` to know when we are recursing.  Additionally, the unwrapping and wrapping I'm doing feels fragile and very much like a hack that may break against future versions of Cerberus, and I'd much prefer something that I know will be stable.  (Note that I've had a very easy time using all of the custom validator and type options, which have been a pleasure to use. Top-level arrays just weren't that easy.)
2. I personally don't think of top-level JSON arrays specifically as an edge case but rather as a general case, but that is of course subject to your point of view.

**Comment by botzill** [comment] 2016-04-04 12:16
Thx @jdotjdot for your code examples, really helpful. After some thought about this we decided  to move our endpoints input data to dicts only. This way we will a standard input data. I think this would be a nice feature in the future as some of this "corner/special cases" can be the basics.

**Comment by nicolaiarocci** [comment] 2016-04-04 12:38
I agree that lists are not a JSON corner case. Thanks to both of you for the great feedback.

**Comment by funkyfuture** [comment] 2016-04-04 20:48
just two more cents:

```
{k: v for k, v in enumerate(a_list)}
```

that's Python 3 and with a little more chars one can do the same with Python 2. or put your list as value into a mapping with one field.

**Comment by khink** [comment] 2021-01-14 16:37
I took me some time to realize that cerberus can already validate the *items* in an arbitrary length list; as documented https://docs.python-cerberus.org/en/stable/validation-rules.html#schema-list. 
Just dropping this here for people like me that are looking to do that:
`schema = {"columns_list": {"type": "list", "required": True, "schema": {"type": COLUMN_SCHEMA}}`

For the people following this issue for different reasons, https://github.com/Fireclunge/cerberus-list-schema might be what you're looking for.

**Comment by svagier** [comment] 2022-01-13 10:47
Based on the great above comment by @khink, here is a concrete example how to validate a list of dicts, in case anyone needs it.
Such a document:
`{
  "columns": [
    {
      "name": "First column",
      "order": 0
    },
    {
      "name": "Second column",
      "order": 1
    }
  ]
}`

Can be validated with this schema:
`{
    'columns': {
      'type': 'list',
      'required': True,
      'schema': {
          'type': 'dict',
          'schema': {
              'name': {'type': 'string', 'required': True},
              'order': {'type': 'integer', 'required': True, 'min': 0}
          }
      }
    }
}`

Hope it helps somebody!

**Comment by yingqiaozheng** [comment] 2022-01-20 19:38
@svagier Your awesome schema example exactly resolved my issue. Thank you so much . I have been googled a lot , this is the best solution. With this schema , I am able to use cerberus as @khink mentioned above. Thank you @khink as well. This makes my day.

**Comment by simonvanderveldt** [comment] 2022-02-03 13:06
Ran into this as well at a customer, was very surprised to learn that a generic schema library is unable to validate normal documents.
@funkyfuture Regarding this statement:
> sorry, i should have read your initial post more carefully. so, no it's not possible and i don't think a method that wraps data and rules into a document and a schema is really necessary.

What makes a document containing a list of things different from a document containing a dict of things?

**Comment by funkyfuture** [comment] 2022-02-03 13:30
> What makes a document containing a list of things different from a document containing a dict of things?

the mere fact that Cerberus was designed to validate Python dictionaries passed from Eve which was an interface to a document-based database at the time.

**Comment by irmo322** [comment] 2022-05-20 22:42
Hi all,

I also regret that cerberus is designed only for documents with a dict at the root, and not a list or any kind of element.

To circumvent this issue I use the following code to validate a document:

``` python
import cerberus

def validate(document, schema, validator_kwargs=None, validate_kwargs=None):
    """
    Validate document using given cerberus-like schema.
    Contrary to official cerberus schema which assumes that document's root is a dict,
    the given schema MUST define the root type which can be of any kind supported by cerberus.
    :param document: the document to validate.
    :param schema:  a cerberus-like schema describing document data.
    :return: the validated document
    """
    validator_kwargs = validator_kwargs or {}
    validate_kwargs = validate_kwargs or {}
    schema_with_root = {'root': schema}
    document_with_root = {'root': document}
    validator = cerberus.Validator(schema=schema_with_root, **validator_kwargs)
    if validator.validate(document_with_root, **validate_kwargs):
        validated_document = validator.document["root"]
    else:
        raise RuntimeError(f"Bad parameters: {validator.errors}")

    return validated_document
```

Some examples of usages:

``` python
validate(
    {'plop': 3},
    {
        'type': 'dict',
        'schema': {'plop': {'type': 'integer'}}
    }  # Would simply be {'plop': {'type': 'integer'}} with official cerberus
)
validate(
    ['plop', 'toto', 'tata'],
    {'type': 'list', 'schema': {'type': 'string'}}
)
validate(
    42,
    {'type': 'integer'}
)
```

I hope this can help other people facing the same issue.

**Comment by gtarabat** [comment] 2022-12-07 17:49
Thank you @irmo322 for the solution. Is it possible to use your proposal to validate a list of dictionaries, 
```
[{"id": 1}, {"id": 2}]
```
as in the question of @botzill?

**Comment by irmo322** [comment] 2022-12-07 19:27
@gtarabat , this code should work (at least it works for me):
``` python
schema = {'type': 'list', 'schema': {
    'type': 'dict', 'schema': {
        'id': {'type': 'integer'}
    }
}}

validate([{"id": 1}, {"id": 2}], schema)
```

**Comment by gtarabat** [comment] 2022-12-07 21:32
Thank you @irmo322. This work as expected. I don't know what I missed in my schema.

**Comment by Talkless** [comment] 2023-03-21 14:26
@irmo322 I don't get it, it does not work:

```
$ python test.py 
Traceback (most recent call last):
  File "/home/vincas/code/opensource/cerberustest/test.py", line 33, in <module>
    main()
  File "/home/vincas/code/opensource/cerberustest/test.py", line 22, in main
    print(v.validate([{"id": 1}, {"id": 2}], schema))
  File "/home/vincas/code/opensource/cerberustest/_venv/lib/python3.9/site-packages/cerberus/validator.py", line 1041, in validate
    self.__init_processing(document, schema)
  File "/home/vincas/code/opensource/cerberustest/_venv/lib/python3.9/site-packages/cerberus/validator.py", line 647, in __init_processing
    self.schema = DefinitionSchema(self, schema)
  File "/home/vincas/code/opensource/cerberustest/_venv/lib/python3.9/site-packages/cerberus/schema.py", line 82, in __init__
    self.validate(schema)
  File "/home/vincas/code/opensource/cerberustest/_venv/lib/python3.9/site-packages/cerberus/schema.py", line 267, in validate
    self._validate(schema)
  File "/home/vincas/code/opensource/cerberustest/_venv/lib/python3.9/site-packages/cerberus/schema.py", line 285, in _validate
    raise SchemaError(self.schema_validator.errors)
cerberus.schema.SchemaError: {'type': ['must be of dict type']}
```

Cerberus 1.3.4, Python 3.9.2 (Debian 11).

**Comment by irmo322** [comment] 2023-03-21 14:55
@Talkless , I guess you are not using my validate function but the original Validator.validate method.

**Comment by Talkless** [comment] 2023-03-22 07:50
Oh, I've missed that fact that this is your custom function... thanks @irmo322 .

@nicolaiarocci Please reconsider implementing this _not_ corner/special case. This would save lot's of troubleshooting time for many developers who hit on the same issue.
